### ISSUE TITLE
Create test cases for UserController

### ISSUE THREAD

**Issue by skashan-ali** [HelpGiver/spring-boot-backend#26]
Create test cases for UserController and create REST API documentation.

**Comment by michal-kk** [comment]
We may split is somehow, easiest would be by controller?

**Comment by skashan-ali** [comment]
You mean change this task with writing test cases for controller?

**Comment by michal-kk** [comment]
Once #23 is closed and we have some framework sorted out, create a task for each controller (so `UserControllerTests` and `HelpRequestControllerTests`)?
